### ISSUE TITLE
Install curl in install_slugs.sh script

### ISSUE THREAD

**Issue by spmaniato** [johnyf/openpromela#3]
I've been using your `install_slugs.sh` script a lot as it makes getting started with slugs on a new machine extremely easy. (Thanks btw!)

Minor suggestion: add `sudo apt-get install curl` to the dependencies section. The script uses it to grab `cudd`. But `curl` doesn't come with the standard Ubuntu installation (neither does OS X, if I remember correctly).

**Comment by slivingston** [comment]
@spmaniato: Does `wget` come with the platforms that motivate your suggestion?

Since the upstream CUDD release is provided via FTP, the argument of favoring one tool with reliable checking of certificates does not apply here, so switching between wget and curl depending on which one the user has could be useful.

**Comment by spmaniato** [comment]
After some Googling I think that Ubuntu comes with `wget` but not `curl` whereas OS X comes with `curl` but not `wget` :astonished:

So yeah. You can either check first and go with the available one or install one and use that.

**Comment by johnyf** [comment]
Thanks @spmaniato, the script now installs `curl` too. The script was already installing a considerable number of dependencies, so `curl` appears to be the least disruptive. At some point in the past, I decided to prefer `curl`, instead of `wget`. I think that the reason was that I was experiencing failures with `wget` encountering redirects (I infer this from the `-L` and `-O` switches that I used, which originated from [this line](https://github.com/tulip-control/tulip-control/blob/c4b3766c9925fe0012ca7d40667ce47358bcc52a/contrib/nessainstall/install.sh#L129) -- I think). A comparison of `curl` vs `wget` can be found [here](http://daniel.haxx.se/docs/curl-vs-wget.html).

For completeness, `curl` is [pre-installed](http://docs.travis-ci.com/user/ci-environment/#Networking-tools) on Travis.
